"""
utils.py — Dataloom v3.0
Export helpers: CSV and Excel (xlsx) generation from query results.
"""

import csv
import io
from datetime import datetime


def export_csv(headers: list, records: list) -> bytes:
    """
    Convert headers + records into a UTF-8 CSV byte string.
    records can be either:
      - list of dicts  (from /api/query response: d.records)
      - list of lists  (raw rows)

    Returns bytes ready to be sent as a file download.
    """
    output = io.StringIO()
    writer = csv.writer(output, quoting=csv.QUOTE_MINIMAL)

    # Write header row
    writer.writerow(headers)

    # Write data rows — handle both dict and list formats
    for row in records:
        if isinstance(row, dict):
            writer.writerow([row.get(h, "") for h in headers])
        else:
            writer.writerow(row)

    return output.getvalue().encode("utf-8-sig")  # utf-8-sig = BOM for Excel compatibility


def export_excel(headers: list, records: list, sheet_name: str = "Results") -> bytes:
    """
    Convert headers + records into an .xlsx byte string using openpyxl.
    Falls back to CSV with an informative error if openpyxl isn't installed.

    Returns bytes ready to be sent as a file download.
    """
    try:
        import openpyxl
        from openpyxl.styles import Font, PatternFill, Alignment
        from openpyxl.utils import get_column_letter
    except ImportError:
        raise RuntimeError(
            "openpyxl is not installed. Run: pip install openpyxl"
        )

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = sheet_name[:31]  # Excel sheet name limit

    # ── Header row styling ────────────────────────────────────────
    HEADER_FILL  = PatternFill("solid", fgColor="1E1B4B")   # deep indigo — matches Dataloom accent
    HEADER_FONT  = Font(bold=True, color="C7D2FE", size=11)  # light indigo text
    HEADER_ALIGN = Alignment(horizontal="left", vertical="center")

    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx, value=header)
        cell.font      = HEADER_FONT
        cell.fill      = HEADER_FILL
        cell.alignment = HEADER_ALIGN

    # ── Data rows ─────────────────────────────────────────────────
    ROW_FONT  = Font(size=10)
    ROW_ALIGN = Alignment(horizontal="left", vertical="center")

    for row_idx, row in enumerate(records, start=2):
        if isinstance(row, dict):
            values = [row.get(h, "") for h in headers]
        else:
            values = list(row)

        for col_idx, value in enumerate(values, start=1):
            cell = ws.cell(row=row_idx, column=col_idx, value=value)
            cell.font      = ROW_FONT
            cell.alignment = ROW_ALIGN

        # Alternate row shading for readability
        if row_idx % 2 == 0:
            for col_idx in range(1, len(headers) + 1):
                ws.cell(row=row_idx, column=col_idx).fill = PatternFill(
                    "solid", fgColor="F8F9FF"
                )

    # ── Auto-size columns ─────────────────────────────────────────
    for col_idx, header in enumerate(headers, start=1):
        col_letter = get_column_letter(col_idx)
        # Sample max content width from header + first 50 rows
        max_len = len(str(header))
        for row_idx in range(2, min(len(records) + 2, 52)):
            cell_val = ws.cell(row=row_idx, column=col_idx).value
            if cell_val is not None:
                max_len = max(max_len, len(str(cell_val)))
        ws.column_dimensions[col_letter].width = min(max_len + 4, 50)

    # ── Freeze header row ─────────────────────────────────────────
    ws.freeze_panes = "A2"

    # ── Add metadata in a second sheet ───────────────────────────
    meta = wb.create_sheet("Info")
    meta["A1"] = "Generated by"
    meta["B1"] = "Dataloom v3.0"
    meta["A2"] = "Exported at"
    meta["B2"] = datetime.now().strftime("%Y-%m-%d %H:%M")
    meta["A3"] = "Rows"
    meta["B3"] = len(records)
    meta["A4"] = "Columns"
    meta["B4"] = len(headers)
    meta.column_dimensions["A"].width = 16
    meta.column_dimensions["B"].width = 28

    # ── Return as bytes ───────────────────────────────────────────
    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer.read()


def make_export_filename(format: str = "csv") -> str:
    """Generate a timestamped export filename."""
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    return f"dataloom_export_{ts}.{format}"
